server:
  port: 8090
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heima
    username: root
    password: 1234
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.56.2
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis:
  type-aliases-package: com.leyou.order.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/*.xml

ly:
  worker:
    workerId: 1
    dataCenterId: 1
  pay:
    wx:
      appID: wx8397f8696b538317
      mchID: 1473426802
      key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
      notifyUrl: http://29jker.natappfree.cc/api/pay/wx/notify
      payType: NATIVE
