server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.56.2
    username: leyou
    password: leyou
    virtual-host: /leyou

ly:
  sms:
    accessKeyID: LTAIGnia8Cuu1m1p # 你自己的accessKeyId
    accessKeySecret: wD7E31R0yxaTBfzaMGNwnLfYJKALdX # 你自己的AccessKeySecret
    signName: 乐优 # 签名名称
    verifyCodeTemplate: SMS_165117892 # 模板名称
    domain: dysmsapi.aliyuncs.com # 域名
    action: SendSMS # API类型，发送短信
    version: 2017-05-25 # API版本，固定值
    regionID: cn-hangzhou # 区域id

