server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heima
    username: root
    password: 1234
  redis:
    host: 192.168.56.2
  rabbitmq:
    host: 192.168.56.2
    username: leyou
    password: leyou
    virtual-host: /leyou
    listener:
      simple:
        retry:
          #开启重试
          enabled: true
          #重试次数
          max-attempts: 3
          #间隔时间
          max-interval: 2000
        default-requeue-rejected: false
        acknowledge-mode: manual
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis:
  type-aliases-package: com.leyou.user.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.leyou: debug

ly:
  encoder:
    crypt:
      secret: ${random.uuid} #随机的密钥，使用uuid
      strength: 10 # 加密强度4~31，决定了密码和盐加密时的运算次数，超过10以后加密耗时会显著增加