server:
  port: 8089
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.56.2
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
